add index.html
massalabs/thyra-plugin-wallet pull request #13
Opened 2022-12-21 12:32 UTC by peterjah

2022-12-21 13:47 UTC, B-Naoufal approved these changes
A nice initiative to have an index in each plugin, it will be needed.

2022-12-22 17:54 UTC, gregLibert requested changes
I think it's easier and cleaner to use a permanent redirect

2022-12-22 17:54 UTC, gregLibert commented on api/wallet_api-v0.yml
> +      operationId: index
```suggestion
      operationId: defaultHTMLPage
```

2022-12-22 17:54 UTC, gregLibert commented on api/wallet_api-v0.yml
> +        - image/png
```suggestion
```

2022-12-22 17:54 UTC, gregLibert commented on api/wallet_api-v0.yml
> +            $ref: "#/definitions/Error"
```suggestion
        "301":
          description: Move to the default endpoint
```

2022-12-22 17:54 UTC, gregLibert commented on internal/handler/web.go
> +}
```suggestion
func IndexHandler(_ operations.DefaultPageParams) middleware.Responder {
	return helper.NewCustomResponder(nil, map[string]string{"Location": "web/index.html"}, http.StatusPermanentRedirect)
}
```

2022-12-22 17:54 UTC, gregLibert commented on web/html/index.html
> +<html>
Not needed anymore

2022-12-23 09:14 UTC, gregLibert approved these changes

2022-12-23 09:14 UTC, merged