300 add update nickname api endpoint
massalabs/thyra-plugin-wallet pull request #301
Opened 2023-06-02 12:20 UTC by Thykof

2023-06-02 12:22 UTC, maxime-carabina approved these changes

2023-06-05 08:17 UTC, peterjah requested changes

2023-06-05 08:17 UTC, peterjah commented on api/walletApi-V0.yml
> +      operationId: ModifyAccountNickname
I think this endpoint should be more generic. do not restrict to nickname. We will probably need to edit some others Account stuffs in the futur
The discription could be something like update account ...

2023-06-05 13:33 UTC, peterjah approved these changes

2023-06-05 13:34 UTC, merged