302 change goswagger to have several slashes in frontend URL
massalabs/thyra-plugin-wallet pull request #304
Opened 2023-06-02 14:30 UTC by Thykof

2023-06-02 22:55 UTC, peterjah approved these changes

2023-06-02 23:00 UTC, B-Naoufal approved these changes

2023-06-05 08:29 UTC, gregLibert requested changes

2023-06-05 08:29 UTC, gregLibert commented on api/server/restapi/configure_massa_wallet.go
> +	const prefix = "/web-app/"
What is web-app ? Can you describe it at least in the contributing ?

2023-06-05 09:10 UTC, merged