update b64 decoding
massalabs/thyra-plugin-wallet pull request #41
Opened 2023-03-02 15:37 UTC by ASAPSegfault

2023-03-03 16:16 UTC, SebastienValla approved these changes
LGTM

2023-03-03 16:37 UTC, peterjah approved these changes

2023-03-06 10:23 UTC, gregLibert requested changes
:no_good: We are not using named return in Golang and it's not done properly.

2023-03-06 10:23 UTC, gregLibert commented on internal/handler/wallet/sign.go
> +func digestOperationAndPubKey(operation *strfmt.Base64, publicKey []byte) (digest [32]byte, resp middleware.Responder) {
```suggestion
func digestOperationAndPubKey(operation *strfmt.Base64, publicKey []byte) ([32]byte, middleware.Responder) {
```

2023-03-06 10:35 UTC, gregLibert approved these changes

2023-03-06 10:36 UTC, merged