adds confirm delete wallet
massalabs/thyra-plugin-wallet pull request #49
Opened 2023-03-14 14:16 UTC by Thykof

2023-03-14 18:28 UTC, thomas-senechal commented on internal/handler/wallet/api.go
> +func AppendEndpoints(api *operations.MassaWalletAPI, passwordPrompter password.Asker, privateKeyPrompter privateKey.Asker, delePrompter delete.Confirmer) {
```suggestion
func AppendEndpoints(api *operations.MassaWalletAPI, passwordPrompter password.Asker, privateKeyPrompter privateKey.Asker, deletePrompter delete.Confirmer) {
```

2023-03-14 18:28 UTC, thomas-senechal commented on internal/handler/wallet/api.go
> +	api.RestWalletDeleteHandler = NewDelete(delePrompter)
```suggestion
	api.RestWalletDeleteHandler = NewDelete(deletePrompter )
```

2023-03-15 13:32 UTC, thomas-senechal approved these changes

2023-03-17 09:55 UTC, ASAPSegfault requested changes

2023-03-17 09:55 UTC, ASAPSegfault commented on README.md
> +Now navigate into <http://localhost:8080>. Note that some feature will not work if
```suggestion
Now navigate into <http://localhost:8080>. Note that some features will not work if
```

2023-03-17 09:55 UTC, ASAPSegfault commented on internal/handler/wallet/delete.go
> +	deleteConfirm delete.Confirmer
This field is poorly named. It doesnt bring any more insight than its type on what it is.

2023-03-17 09:55 UTC, ASAPSegfault commented on pkg/delete/confirm.go
> +// Verifies at compilation time that FynePrompter implements Asker interface.
```suggestion
// Verifies at compilation time that FynePrompter implements Confirmer interface.
```

2023-03-17 09:55 UTC, ASAPSegfault commented on pkg/delete/confirm.go
> +// PasswordDeleteDialog displays a password dialog with the given nickname and ask confirmation for delete the account.
```suggestion
// PasswordDeleteDialog displays a password dialog with the given nickname and ask confirmation to delete the account.
```

2023-03-23 11:08 UTC, ASAPSegfault approved these changes

2023-03-23 11:59 UTC, merged